apiVersion: v1
entries:
  exastro-it-automation:
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2022-10-19T18:05:03.494631124+09:00"
    description: Exastro IT Automation is an Open Source Framework for digitizing
      and centrally managing the system configuration.
    digest: 3c5c6fb3b1eb01cafe61d5c4443f06036e336eec098b372bc4c76d0de3c08374
    home: https://exastro-suite.github.io/
    icon: https://exastro-suite.github.io/docs/asset/logo/exastro/Exastro-logomark2-rgb.svg
    keywords:
    - exastro
    - exastro-it-automation
    maintainers:
    - email: contact@exastro.jp.nec.com
      name: NEC Corporation
    name: exastro-it-automation
    sources:
    - https://github.com/exastro-suite/exastro-it-automation
    type: application
    urls:
    - exastro-it-automation-1.0.0.tgz
    version: 1.0.0
generated: "2022-10-19T18:05:03.478573935+09:00"
