apiVersion: v1
entries:
  exastro-it-automation:
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2022-10-20T21:23:46.998574748+09:00"
    description: Exastro IT Automation is an Open Source Framework for digitizing
      and centrally managing the system configuration.
    digest: e93c774dd5f886e7924314d2de85dc0804b4bf2c2df80a0083f226db3ff9de1f
    home: https://exastro-suite.github.io/
    icon: https://exastro-suite.github.io/docs/asset/logo/exastro/Exastro-logomark2-rgb.svg
    keywords:
    - exastro
    - exastro-it-automation
    maintainers:
    - email: contact@exastro.jp.nec.com
      name: NEC Corporation
    name: exastro-it-automation
    sources:
    - https://github.com/exastro-suite/exastro-it-automation
    type: application
    urls:
    - exastro-it-automation-1.0.2.tgz
    version: 1.0.2
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2022-10-20T21:23:46.992338987+09:00"
    description: Exastro IT Automation is an Open Source Framework for digitizing
      and centrally managing the system configuration.
    digest: 37d1086f5d1f2f816bacb6a486f88d7409b3485bba4dbc368bb7a96956e1e88d
    home: https://exastro-suite.github.io/
    icon: https://exastro-suite.github.io/docs/asset/logo/exastro/Exastro-logomark2-rgb.svg
    keywords:
    - exastro
    - exastro-it-automation
    maintainers:
    - email: contact@exastro.jp.nec.com
      name: NEC Corporation
    name: exastro-it-automation
    sources:
    - https://github.com/exastro-suite/exastro-it-automation
    type: application
    urls:
    - exastro-it-automation-1.0.1.tgz
    version: 1.0.1
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2022-10-20T21:23:46.985469038+09:00"
    description: Exastro IT Automation is an Open Source Framework for digitizing
      and centrally managing the system configuration.
    digest: 3c5c6fb3b1eb01cafe61d5c4443f06036e336eec098b372bc4c76d0de3c08374
    home: https://exastro-suite.github.io/
    icon: https://exastro-suite.github.io/docs/asset/logo/exastro/Exastro-logomark2-rgb.svg
    keywords:
    - exastro
    - exastro-it-automation
    maintainers:
    - email: contact@exastro.jp.nec.com
      name: NEC Corporation
    name: exastro-it-automation
    sources:
    - https://github.com/exastro-suite/exastro-it-automation
    type: application
    urls:
    - exastro-it-automation-1.0.0.tgz
    version: 1.0.0
generated: "2022-10-20T21:23:46.976083865+09:00"
